learning_logs/urls.py
'''defines URL schemes for learning_logs'''
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
	#home page
	path('', views.index, name='index'),
	#all topics presentation
	path('topics/', views.topics, name='topics'),
	#page with information for the theme
	path('topics/<int:topic_id>', views.topic, name='topic'),
	#page for adding a new topic
	path('new_topic/', views.new_topic, name='new_topic'),
	#page for adding a new entry
	path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
	#page for editing the entry
	path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

lerning_log/urls.py
# from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
]

users/urls.py
'''defines URL schemes for users'''
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
	#entring account
	path('login/', views.login_user, name='login_user'),
	#leaving account
	path('logout/', views.logout_user, name='logout_user'),
	#register page
	path('register/', views.register_user, name='register_user'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	'''A theme that user investigate'''
	text = models.CharField(max_length=250)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		'''returns string form of model'''
		return self.text

class Entry(models.Model):
	'''Information investigated by user on the topic'''
	topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		'''returns string form of model'''
		return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 100})}

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(UserCreationForm, forms.Form):
	class Meta:
		model = User
		fields = ['username', 'password1', 'password2']

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
	'''home page of the application Learning Log'''
	return render(request, 'learning_logs/index.html')

@login_required(login_url='/users/login/')
def topics(request):
	'''all topics presentation'''
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)

@login_required(login_url='/users/login/')
def topic(request, topic_id):
	'''all the notes of the topic'''
	topic = get_object_or_404(Topic, id=topic_id)
	#ckeck for afflication to the user
	if topic.owner != request.user:
		raise Http404
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)

@login_required(login_url='/users/login/')
def new_topic(request):
	'''define a new topic'''
	if request.method != 'POST':
		#data was not sent; create empty form
		form = TopicForm()
	else:
		#POST-data sent; handle data
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))

	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)

@login_required(login_url='/users/login/')
def new_entry(request, topic_id):
	'''define a new entry for the defined topic'''
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		#data was not sent; create empty form
		form = EntryForm()
	else:
		#POST-data sent; handle data
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required(login_url='/users/login/')
def edit_entry(request, entry_id):
	'''edits the existing entry'''
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#Start request; Form fills by current text
		form = EntryForm(instance=entry)
	else:
		#Sending data by 'POST'; handle data
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, RegisterForm

def login_user(request):
	'''user enter by username and password'''
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
			if user is not None and user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('learning_logs:index'))

	form = LoginForm()
	context = {'form': form}
	return render(request, 'users/login.html', context)

def logout_user(request):
	'''user finishes work with the app'''
	logout(request)
	return HttpResponseRedirect(reverse('learning_logs:index'))

def register_user(request):
	'''register a new user'''
	if request.method != 'POST':
		#returns blank registration form
		form = RegisterForm()
	else:
		#handling of the registration form
		form = RegisterForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			#authentication and entering of the new user
			authenticated_user = authenticate(username=new_user.username,
				password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('learning_logs:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)



	

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Learning Log</title>
	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>
<body>
	<!-- navigation panel -->
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
						data-toggle="collapse" data-target="#navbar"
						aria-expanded="false" aria-controls="navbar">
					&#9776;							
				</button>
				<a href="{% url 'learning_logs:index' %}" class="navbar-brand">
					Learning Log
				</a>
			</div>

			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						<a href="{% url 'learning_logs:topics' %}">Topics</a>
					</li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li>
						<a>
							Hello, {{ user.username }}.
						</a>
					</li>
					<li>
						<a href="{% url 'users:logout_user' %}">log out</a>
					</li>
					{% else %}
					<li>
						<a href="{% url 'users:register_user' %}">register</a>
					</li>
					<li>
						<a href="{% url 'users:login_user' %}">log in</a>
					</li>
					{% endif %}
				</ul>
			</div> <!-- /.nav-collapse -->

			<div class="container">
				<div class="page-header">
					{% block header %} {% endblock header %}
				</div>
				<div>
					{% block content %} {% endblock content %}
				</div>
			</div><!-- /.container -->

		</div>
	</nav>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
<h2>
	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</h2>
{% endblock header %}

{% block content %}
<h3>
	Edit entry:
</h3>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">Save changes</button>
	{% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
<div class="jumbotron">
	<h1>Track your learning.</h1>
</div>
{% endblock header %}

{% block content %}
<h2>
	{% if user.is_authenticated %}
		Make your own Learning Log, and list the topics you're learning about.
	{% else %}
		<a href="{% url 'users:register_user' %}">Register an account</a>
		to make your own Learning Log, and list the topics you're learning about.	
	{% endif %}
</h2>
<h2>
	Whenever you learn something new about the topic, 
	make an entry summarizing what you've learned.
</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
<h2>
	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</h2>
{% endblock header %}

{% block content %}
<h3>
	Add a new entry:
</h3>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">Add entry</button>
	{% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method="POST" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">Add topic</button>
	{% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h2>
	Topic: {{ topic }}
</h2>
{% endblock header %}

{% block content %}
<p>
	<a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
</p>
{% for entry in entries %}
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3>
				{{ entry.date_added|date:'M d, Y H:i' }}
				<small>
					<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
				</small>
			</h3>
		</div>
		<div class="panel-body">
			{{ entry.text|linebreaks }}
		</div>
	</div> <!-- panel -->
{% empty %} 
	There are no entries for this topic yet
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h2>
	Topics
</h2>
{% endblock header %}

{% block content %}
<ul>
	{% for topic in topics %}
		<li>
			<h3>
				<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</h3>
		</li> 
	{% empty %} 
		<li>No topics have been added yet</li> 
	{% endfor %}
</ul>

<h3>
	<a href="{% url 'learning_logs:new_topic' %}">Add new topic</a>
</h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
	<h2>Log in to your account</h2>
{% endblock header %}

{% block content %}
	<form action="{% url 'users:login_user' %}" method="POST" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
	<button name="submit" class="btn btn-primary">log in</button>
	{% endbuttons %}
	<input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
	</form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
<h2>Register:</h2>
{% endblock header %}

{% block content %}
	<form action="{% url 'users:register_user' %}" method="POST" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% if error %}
	<p>{{ error }}</p>
	{% endif %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">Register</button>
	{% endbuttons %}
	<input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
	</form>
{% endblock content %}